server:
 port: 8081
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/online_store
  username: root
  password: root
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect

 liquibase:
  enabled: true
  change-log: classpath:/db/changelog.xml



